### ISSUE TITLE
Text input for search not working in some apps [YouTube, Prime Video]

### ISSUE THREAD

**Issue by iamprem** [jcarbaugh/python-roku#57]
I'm trying to use ```roku.literal("Text")``` to input text for Youtube search by following this documentation. But none of the text values are being accepted by this search page and it remains blank.

https://github.com/jcarbaugh/python-roku#entering-text

I verified ```roku.literal``` working in Netflix, Roku Channel and the Roku's native search app. Any idea why this inconsistency in text input behaviour?

**Comment by jcarbaugh** [comment]
@iamprem I just tried it out and can verify that literal is not working in YouTube. Unfortunately, I think this is ultimately due to how YouTube built their app. I imagine they are either using custom controls or are not handling the literal command. I'm not sure there's much that can be done about it 😕
